src/Entity/Vacation.php
<?php

namespace App\Entity;

use App\Repository\VacationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VacationRepository::class)]
class Vacation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $initial_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $final_date = null;

    #[ORM\ManyToOne(inversedBy: 'vacations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $username = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInitialDate(): ?\DateTimeInterface
    {
        return $this->initial_date;
    }

    public function setInitialDate(\DateTimeInterface $initial_date): static
    {
        $this->initial_date = $initial_date;

        return $this;
    }

    public function getFinalDate(): ?\DateTimeInterface
    {
        return $this->final_date;
    }

    public function setFinalDate(\DateTimeInterface $final_date): static
    {
        $this->final_date = $final_date;

        return $this;
    }

    public function getUsername(): ?User
    {
        return $this->username;
    }

    public function setUsername(?User $username): static
    {
        $this->username = $username;

        return $this;
    }
}

src/Form/VacationType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Vacation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VacationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('initial_date', null, [
                'widget' => 'single_text',
            ])
            ->add('final_date', null, [
                'widget' => 'single_text',
            ])
            ->add('username', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vacation::class,
        ]);
    }
}

src/Controller/VacationController.php
<?php

namespace App\Controller;

use App\Entity\Vacation;
use App\Form\VacationType;
use App\Repository\VacationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/vacation')]
final class VacationController extends AbstractController
{
    #[Route(name: 'app_vacation_index', methods: ['GET'])]
    public function index(VacationRepository $vacationRepository): Response
    {
        return $this->render('vacation/index.html.twig', [
            'vacations' => $vacationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_vacation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $vacation = new Vacation();
        $form = $this->createForm(VacationType::class, $vacation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($vacation);
            $entityManager->flush();

            return $this->redirectToRoute('app_vacation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vacation/new.html.twig', [
            'vacation' => $vacation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_vacation_show', methods: ['GET'])]
    public function show(Vacation $vacation): Response
    {
        return $this->render('vacation/show.html.twig', [
            'vacation' => $vacation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_vacation_edit', methods: ['PUT'])]
    public function edit(Request $request, Vacation $vacation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VacationType::class, $vacation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_vacation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vacation/edit.html.twig', [
            'vacation' => $vacation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_vacation_delete', methods: ['DELETE'])]
    public function delete(Request $request, Vacation $vacation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vacation->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($vacation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_vacation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/vacation/_delete_form.html.twig
<form method="post" action="{{ path('app_vacation_delete', {'id': vacation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vacation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/vacation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/vacation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vacation{% endblock %}

{% block body %}
    <h1>Edit Vacation</h1>

    {{ include('vacation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_vacation_index') }}">back to list</a>

    {{ include('vacation/_delete_form.html.twig') }}
{% endblock %}

templates/vacation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vacation index{% endblock %}

{% block body %}
    <h1>Vacation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Initial_date</th>
                <th>Final_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vacation in vacations %}
            <tr>
                <td>{{ vacation.id }}</td>
                <td>{{ vacation.initialDate ? vacation.initialDate|date('Y-m-d') : '' }}</td>
                <td>{{ vacation.finalDate ? vacation.finalDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_vacation_show', {'id': vacation.id}) }}">show</a>
                    <a href="{{ path('app_vacation_edit', {'id': vacation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_vacation_new') }}">Create new</a>
{% endblock %}

templates/vacation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Vacation{% endblock %}

{% block body %}
    <h1>Create new Vacation</h1>

    {{ include('vacation/_form.html.twig') }}

    <a href="{{ path('app_vacation_index') }}">back to list</a>
{% endblock %}

templates/vacation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vacation{% endblock %}

{% block body %}
    <h1>Vacation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vacation.id }}</td>
            </tr>
            <tr>
                <th>Initial_date</th>
                <td>{{ vacation.initialDate ? vacation.initialDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Final_date</th>
                <td>{{ vacation.finalDate ? vacation.finalDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vacation_index') }}">back to list</a>

    <a href="{{ path('app_vacation_edit', {'id': vacation.id}) }}">edit</a>

    {{ include('vacation/_delete_form.html.twig') }}
{% endblock %}