src/Entity/Holiday.php
<?php

namespace App\Entity;

use App\Repository\HolidayRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HolidayRepository::class)]
class Holiday
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $every_year = null;

    #[ORM\Column]
    private ?bool $holiday_bridge = null;

    #[ORM\Column]
    private ?bool $half_day_friday = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getEveryYear(): ?int
    {
        return $this->every_year;
    }

    public function setEveryYear(int $every_year): static
    {
        $this->every_year = $every_year;

        return $this;
    }

    public function isHolidayBridge(): ?bool
    {
        return $this->holiday_bridge;
    }

    public function setHolidayBridge(bool $holiday_bridge): static
    {
        $this->holiday_bridge = $holiday_bridge;

        return $this;
    }

    public function isHalfDayFriday(): ?bool
    {
        return $this->half_day_friday;
    }

    public function setHalfDayFriday(bool $half_day_friday): static
    {
        $this->half_day_friday = $half_day_friday;

        return $this;
    }
}

src/Form/HolidayType.php
<?php

namespace App\Form;

use App\Entity\Holiday;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HolidayType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('date', null, [
                'widget' => 'single_text',
            ])
            ->add('every_year')
            ->add('holiday_bridge')
            ->add('half_day_friday')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Holiday::class,
        ]);
    }
}

src/Controller/HolidayController.php
<?php

namespace App\Controller;

use App\Entity\Holiday;
use App\Form\HolidayType;
use App\Repository\HolidayRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/holiday')]
final class HolidayController extends AbstractController
{
    #[Route(name: 'app_holiday_index', methods: ['GET'])]
    public function index(HolidayRepository $holidayRepository): Response
    {
        return $this->render('holiday/index.html.twig', [
            'holidays' => $holidayRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_holiday_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $holiday = new Holiday();
        $form = $this->createForm(HolidayType::class, $holiday);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($holiday);
            $entityManager->flush();

            return $this->redirectToRoute('app_holiday_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('holiday/new.html.twig', [
            'holiday' => $holiday,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_holiday_show', methods: ['GET'])]
    public function show(Holiday $holiday): Response
    {
        return $this->render('holiday/show.html.twig', [
            'holiday' => $holiday,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_holiday_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Holiday $holiday, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(HolidayType::class, $holiday);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_holiday_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('holiday/edit.html.twig', [
            'holiday' => $holiday,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_holiday_delete', methods: ['POST'])]
    public function delete(Request $request, Holiday $holiday, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$holiday->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($holiday);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_holiday_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/holiday/_delete_form.html.twig
<form method="post" action="{{ path('app_holiday_delete', {'id': holiday.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ holiday.id) }}">
    <button class="btn">Delete</button>
</form>

templates/holiday/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/holiday/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Holiday{% endblock %}

{% block body %}
    <h1>Edit Holiday</h1>

    {{ include('holiday/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_holiday_index') }}">back to list</a>

    {{ include('holiday/_delete_form.html.twig') }}
{% endblock %}

templates/holiday/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Holiday index{% endblock %}

{% block body %}
    <h1>Holiday index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Date</th>
                <th>Every_year</th>
                <th>Holiday_bridge</th>
                <th>Half_day_friday</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for holiday in holidays %}
            <tr>
                <td>{{ holiday.id }}</td>
                <td>{{ holiday.name }}</td>
                <td>{{ holiday.date ? holiday.date|date('Y-m-d') : '' }}</td>
                <td>{{ holiday.everyYear }}</td>
                <td>{{ holiday.holidayBridge ? 'Yes' : 'No' }}</td>
                <td>{{ holiday.halfDayFriday ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_holiday_show', {'id': holiday.id}) }}">show</a>
                    <a href="{{ path('app_holiday_edit', {'id': holiday.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_holiday_new') }}">Create new</a>
{% endblock %}

templates/holiday/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Holiday{% endblock %}

{% block body %}
    <h1>Create new Holiday</h1>

    {{ include('holiday/_form.html.twig') }}

    <a href="{{ path('app_holiday_index') }}">back to list</a>
{% endblock %}

templates/holiday/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Holiday{% endblock %}

{% block body %}
    <h1>Holiday</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ holiday.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ holiday.name }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ holiday.date ? holiday.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Every_year</th>
                <td>{{ holiday.everyYear }}</td>
            </tr>
            <tr>
                <th>Holiday_bridge</th>
                <td>{{ holiday.holidayBridge ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Half_day_friday</th>
                <td>{{ holiday.halfDayFriday ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_holiday_index') }}">back to list</a>

    <a href="{{ path('app_holiday_edit', {'id': holiday.id}) }}">edit</a>

    {{ include('holiday/_delete_form.html.twig') }}
{% endblock %}